spring:
  application:
    name: coreWebMy
  profiles:
    active: developer

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json

security:
  basic:
    enabled: false
